from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'main.views.home', name = 'home'),
    #url(r'^new-entry/$', 'main.views.new_entry', name = 'new_entry'),
    url(r'^select-surveyor/(?P<proj_pk>\d+)/$', 'main.views.select_surveyor',
        name = 'select-surveyor'),
    url(r'^add-completed-entry/(?P<role_id>\d+)/$', 'main.views.add_completed_entry',
        name = 'add-completed-entry'),
    url(r'^add-completed-entry-done/(?P<role_id>\d+)/$', 'main.views.add_completed_entry_done',
        name = 'add-completed-entry-done'),
    url(r'^add-uncompleted-entry/(?P<role_id>\d+)/$', 'main.views.add_uncompleted_entry',
        name = 'add-uncompleted-entry'),
    url(r'^add-uncompleted-entry-done/(?P<role_id>\d+)/$', 'main.views.add_uncompleted_entry_done',
        name = 'add-uncompleted-entry-done'),
    url(r'^manage-uids/(?P<role_id>\d+)/$', 'main.views.manage_uids',
        name = 'manage-uids'),
    url(r'^manage-uids/(?P<role_id>\d+)/subordinate/(?P<sub_role>\d+)/$',
        'main.views.manage_sub_uids', name = 'manage-sub-uids'),
    url(r'^get-error-types/$', 'main.views.get_error_types',
        name = 'get_error_types'),
)
