from django.conf.urls.defaults import patterns, url

urlpatterns = patterns('',
    url(r'^$', 'main.views.home', name = 'home'),
    #url(r'^new-entry/$', 'main.views.new_entry', name = 'new_entry'),
    url(r'^update-uids/(?P<proj_pk>\d+)/$', 'main.views.update_uids',
        name = 'update-uids'),
    url(r'^update-uids/(?P<proj_pk>\d+)/completed/(?P<role_id>\d+)/$', 'main.views.add_completed_entry',
        name = 'add-completed-entry'),
    url(r'^add-completed-entry-done/(?P<role_id>\d+)/$', 'main.views.add_completed_entry_done',
        name = 'add-completed-entry-done'),
    url(r'^update-uids/(?P<proj_pk>\d+)/not-completed/(?P<role_id>\d+)/$', 'main.views.add_uncompleted_entry',
        name = 'add-uncompleted-entry'),
    url(r'^add-uncompleted-entry-done/(?P<role_id>\d+)/$', 'main.views.add_uncompleted_entry_done',
        name = 'add-uncompleted-entry-done'),
    url(r'^manage-uids/(?P<role_id>\d+)/$', 'main.views.manage_uids',
        name = 'manage-uids'),
    url(r'^manage-uids/(?P<role_id>\d+)/subordinate/(?P<sub_role>\d+)/$',
        'main.views.manage_sub_uids', name = 'manage-sub-uids'),
    url(r'^manage-uids/(?P<role_id>\d+)/auto-distribute/$',
        'main.views.auto_distribute_uids', name = 'auto-distribute-uids'),
    url(r'^import-uids/(?P<role_id>\d+)/$', 'main.views.import_uids',
        name = 'import-uids'),
    url(r'^get-error-types/(?P<role_id>\d+)/$', 'main.views.get_error_types',
        name = 'get_error_types'),
    url(r'^get-uid-list/(?P<role_id>\d+)/$', 'main.views.get_uid_list',
        name = 'get_uid_list'),
    url(r'^get-questions/(?P<role_id>\d+)/$', 'main.views.get_questions',
        name = 'get_questions'),
    url(r'^get-choices/(?P<role_id>\d+)/$', 'main.views.get_choices',
        name = 'get_choices'),

)
